# The Travis CI is our full-fledged CI, but this Github workflow
# runs the same tests. The GH workflow UI makes it simpler to hone
# in on the step that failed.

name: 💡🏠

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: git clone
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Set up protoc
      uses: arduino/setup-protoc@7ad700d
      with:
        version: '3.7.1'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install protobuf==3.7.1

    - run: yarn --frozen-lockfile
    - run: yarn build-all
    - run: yarn diff:sample-json
    - run: yarn type-check
    - run: yarn lint
    - run: yarn test-proto # Run before unit-core because the roundtrip json is needed for proto tests.

    # Run tests that require headfull Chrome.
    - run: sudo apt-get install xvfb
    - name: yarn unit
      run: xvfb-run --auto-servernum yarn unit
    - name: yarn test-clients
      run: xvfb-run --auto-servernum yarn test-clients
    - name: yarn test-bundle
      run: xvfb-run --auto-servernum yarn test-bundle
    - name: yarn test-docs
      run: xvfb-run --auto-servernum yarn test-docs

    - run: yarn test-lantern
    - run: yarn test-legacy-javascript
    - run: yarn i18n:checks
    - run: yarn dogfood-lhci

    - name: Upload dist/
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

    # buildtracker runs `git merge-base HEAD origin/master` which needs more history than depth=1. https://github.com/paularmstrong/build-tracker/issues/106
    - name: Deepen git fetch (for buildtracker)
      run: git fetch --deepen=100
    - name: Store in buildtracker
      # TODO(paulirish): Don't allow this to fail the build. https://github.com/paularmstrong/build-tracker/issues/200
      run: yarn bt-cli upload-build || true
      env:
        # https://buildtracker.dev/docs/guides/github-actions#configuration
        BT_API_AUTH_TOKEN: ${{ secrets.BT_API_AUTH_TOKEN }}

    # Fail if any changes were written to source files (ex, from: build/build-cdt-lib.js).
    - run: git diff --exit-code

  smoke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        invert: [false, true]
      # e.g. if smoke 0 fails, continue with smoke 1 anyway
      fail-fast: false
    env:
      # The smokehouse tests run by job smoke 0. smoke-1 will run the rest.
      SMOKE_GROUP_1: a11y oopif pwa pwa2 pwa3 dbw redirects errors offline
    name: smoke ${{ strategy.job-index }}

    steps:
    - name: git clone
      uses: actions/checkout@v2
  
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - run: yarn --frozen-lockfile
    - name: Run smoke tests
      run: xvfb-run --auto-servernum yarn smoke --debug -j=1 --retries=2 --invert ${{ matrix.invert }} $SMOKE_GROUP_1
